[package]
name = "paralel-dfs"
version = "0.1.1"
authors = ["Nikola Stoyanov <ns.barzakov@gmail.com>"]

[dependencies]
clap = "^2.23.3"
crossbeam = "^0.2.10"
rand = "^0.3.15"

[profile.release]
lto = true
